"""Standardizer and post-processor for Markdown output.

Cleans up raw markdown generated by parsers by standardizing bullets,
normalizing whitespace/newlines, and refining table structures.
"""

import re


class Standardizer:
    """Post-processor for cleaning and standardizing raw Markdown output."""

    @classmethod
    def standardize(cls, raw_md: str) -> str:
        """Apply standardization rules to raw Markdown content.

        Args:
            raw_md: Raw markdown text string.

        Returns:
            Cleaned and standardized markdown text.
        """
        if not raw_md:
            return ""

        text = raw_md

        # 1. Standardize bullet characters (*, + at line starts with spacing) to '-'
        text = re.sub(r"^(\s*)[*+]\s+", r"\1- ", text, flags=re.MULTILINE)

        # 2. Clean table formatting: fix cell spacing and inline newlines
        text = cls._clean_tables(text)

        # 3. Trim trailing whitespace on each line
        lines = [line.rstrip() for line in text.splitlines()]
        text = "\n".join(lines)

        # 4. Collapse 3 or more consecutive newlines into max 2 newlines (\n\n)
        text = re.sub(r"\n{3,}", "\n\n", text)

        # 5. Ensure single newline at end of file
        return text.strip() + "\n"

    @classmethod
    def _clean_tables(cls, text: str) -> str:
        """Process markdown tables to ensure proper formatting and escape internal breaks."""
        lines = text.splitlines()
        cleaned_lines = []
        in_table = False

        for line in lines:
            stripped = line.strip()
            # Detect pipe table lines
            if stripped.startswith("|") and stripped.endswith("|"):
                in_table = True
                # Format table line: trim internal cell spacing cleanly
                cells = [c.strip() for c in stripped.split("|")]
                # Strip leading and trailing empty cell splits from leading/trailing pipes
                if len(cells) > 1 and cells[0] == "":
                    cells = cells[1:]
                if len(cells) > 1 and cells[-1] == "":
                    cells = cells[:-1]

                # Check if it's a delimiter line (e.g. | --- | --- |)
                if all(re.match(r"^:?-+:?$", c) for c in cells):
                    formatted_line = "| " + " | ".join(c if c else "---" for c in cells) + " |"
                else:
                    # Clean content cells: replace raw newlines with <br> if any slipped in
                    cleaned_cells = [c.replace("\n", "<br>") for c in cells]
                    formatted_line = "| " + " | ".join(cleaned_cells) + " |"
                cleaned_lines.append(formatted_line)
            else:
                if in_table:
                    in_table = False
                cleaned_lines.append(line)

        return "\n".join(cleaned_lines)
