import re
import base64
from typing import BinaryIO, Any
from markitdown import DocumentConverterResult
from markitdown.converters._docx_converter import DocxConverter
from markitdown.converters._html_converter import HtmlConverter
from markitdown.converter_utils.docx.pre_process import pre_process_docx
import mammoth

from converter_engine.core.ocr_engine import extract_text_from_image

class DOCXParser(DocxConverter):
    """
    Custom MarkItDown plugin for DOCX files.
    Overrides mammoth's image handler to inject offline OCR via pytesseract.
    """
    def convert(self, file_stream: BinaryIO, stream_info, **kwargs: Any) -> DocumentConverterResult:
        def _image_handler(image):
            with image.open() as image_stream:
                image_bytes = image_stream.read()
            
            ocr_text = extract_text_from_image(image_bytes)
            encoded_src = base64.b64encode(image_bytes).decode("ascii")
            src = f"data:{image.content_type};base64,{encoded_src}"
            
            attrs = {"src": src}
            if ocr_text:
                # Encode OCR text into base64 and prepend a unique alphanumeric prefix
                # to avoid markdownify escaping characters like underscores.
                b64_ocr = base64.b64encode(ocr_text.encode("utf-8")).decode("ascii")
                attrs["alt"] = f"OCRB64{b64_ocr}"
            else:
                attrs["alt"] = "Image"
                
            return attrs

        pre_process_stream = pre_process_docx(file_stream)
        style_map = kwargs.get("style_map", None)
        
        # Convert to HTML via mammoth with our custom image handler
        result = mammoth.convert_to_html(
            pre_process_stream, 
            convert_image=mammoth.images.inline(_image_handler),
            style_map=style_map
        )
        
        # Convert HTML to Markdown
        html_converter = HtmlConverter()
        md_result = html_converter.convert_string(result.value, **kwargs)
        md_content = md_result.markdown
        
        # Post-process the markdown to inject the requested blockquote format
        def replacer(match):
            b64_ocr = match.group(1)
            src = match.group(2)
            try:
                ocr_text = base64.b64decode(b64_ocr).decode("utf-8")
                replacement = f"![Image]({src})\n> **[Image Text Extraction]**\n"
                for line in ocr_text.splitlines():
                    if line.strip():
                        replacement += f"> {line.strip()}\n"
                return replacement.strip()
            except Exception:
                return f"![Image]({src})"
                
        # Regex matches the exact alt text pattern generated by our image handler
        pattern = re.compile(r'!\[OCRB64([a-zA-Z0-9+/=]+)\]\(([^\)]+)\)')
        md_content = pattern.sub(replacer, md_content)

        return DocumentConverterResult(markdown=md_content)
